# create github actions ci.yml file for go and nodejs project with unit tests for bugtracker-backend which will run for a push to main branch and pull request to main branch
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit-tests-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
          cache-dependency-path: bug-tracker-backend/go.sum

      - name: EXECUTE BACKEND UNIT TESTS
        working-directory: ./bug-tracker-backend
        run: go test -v ./... 