pipeline{
    agent any

    stages {
        stage('UNIT TESTS BACKEND') {
            agent{
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                    args '-e GOCACHE=/tmp/go-cache -e GOPATH=/tmp/go'
                    //image 'golang:1.20'
                    //args '-v /go/pkg/mod:/go/pkg/mod -v $WORKSPACE/bugtracker-backend:/go/src/bugtracker-backend -w /go/src/bugtracker-backend'
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                    
                }
            }
        }
        stage('UNIT TESTS FRONTEND') {
            agent{
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                    args '-v $WORKSPACE/bugtracker-frontend:/usr/src/app -w /usr/src/app'
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh 'npm install'
                    sh 'npm test -- --watchAll=false'
                }
            }
        }   
        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}